# =============================================================================
# SATRAK — Cross-language developer entrypoints
# =============================================================================
# The Makefile is the single "how do I run X" surface across the polyglot repo
# (TypeScript via pnpm/turbo, Python via venv, everything via docker-compose),
# so a new engineer never has to remember per-tool incantations.
# -----------------------------------------------------------------------------

.DEFAULT_GOAL := help
SHELL := /bin/bash
COMPOSE := docker compose -f infra/docker-compose/docker-compose.yml
API_DIR := apps/api

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

# --- Bootstrap ---------------------------------------------------------------
.PHONY: install
install: install-js install-py ## Install all dependencies (JS + Python)

.PHONY: install-js
install-js: ## Install JS/TS workspace dependencies
	pnpm install

.PHONY: install-py
install-py: ## Create the API virtualenv and install Python deps
	cd $(API_DIR) && python -m venv .venv && \
		. .venv/Scripts/activate 2>/dev/null || . .venv/bin/activate; \
		pip install -U pip && pip install -e ".[dev]"

# --- Local dev ---------------------------------------------------------------
.PHONY: dev
dev: ## Run web + api dev servers via turbo (requires infra up)
	pnpm run dev

.PHONY: up
up: ## Start the full local stack (postgis, redis, api, web) in Docker
	$(COMPOSE) up -d --build

.PHONY: down
down: ## Stop the local stack
	$(COMPOSE) down

.PHONY: logs
logs: ## Tail stack logs
	$(COMPOSE) logs -f

# --- Database ----------------------------------------------------------------
.PHONY: migrate
migrate: ## Apply Alembic migrations to head
	cd $(API_DIR) && alembic upgrade head

.PHONY: migration
migration: ## Create a new autogenerated migration (msg="...")
	cd $(API_DIR) && alembic revision --autogenerate -m "$(msg)"

# --- Quality -----------------------------------------------------------------
.PHONY: lint
lint: ## Lint everything (JS + Python)
	pnpm run lint
	cd $(API_DIR) && ruff check .

.PHONY: format
format: ## Format everything (JS + Python)
	pnpm run format
	cd $(API_DIR) && black . && isort .

.PHONY: typecheck
typecheck: ## Type-check everything
	pnpm run typecheck
	cd $(API_DIR) && mypy app

.PHONY: test
test: ## Run all tests
	pnpm run test
	cd $(API_DIR) && pytest

.PHONY: clean
clean: ## Remove build artifacts and caches
	rm -rf node_modules **/node_modules **/.next **/.turbo **/dist **/coverage
	find . -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
